server.port=8081
spring.application.name=auth-service

spring.profiles.active=docker
spring.config.import=optional:file:.env[.properties]
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.ejb.naming_strategy=org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl

spring.liquibase.change-log=classpath:db/changelog/db.changelog-master.yaml

jwt.secret=${JWT_SECRET:Y0VyU2VjcmV0S2V5Rm9ySldUVG9rZW5TaWduaW5nMTIzNDU2Nzg5MEFCQ0RFRkdISUpLTE1OT1BRUlNUVVZXWFla}
jwt.access-token-expiration=3600000
jwt.refresh-token-expiration=86400000

spring.output.ansi.enabled=ALWAYS
logging.pattern.console=%d{yyyy-MM-dd HH:mm:ss.SSS} %clr(%-5level){cyan} [%thread] %cyan(%logger{15}) - %msg%n

admin.bootstrap.enabled=${ADMIN_BOOTSTRAP_ENABLED:false}
admin.bootstrap.login=${ADMIN_BOOTSTRAP_LOGIN:admin@example.com}
admin.bootstrap.password=${ADMIN_BOOTSTRAP_PASSWORD:ChangeMe123!}
admin.bootstrap.user-id=${ADMIN_BOOTSTRAP_USER_ID:1}